use std::sync::Once;

static INIT: Once = Once::new();

pub fn init(lang: Option<String>) {
    INIT.call_once(|| {
        if let Some(l) = lang {
            if l != "system" && !l.is_empty() {
                std::env::set_var("LANGUAGE", &l);
                // Also set LANG as fallback, though LANGUAGE takes precedence for gettext
                std::env::set_var("LANG", format!("{}.UTF-8", l));
            }
        }

        gettextrs::setlocale(gettextrs::LocaleCategory::LcAll, "");

        // Use the LOCALE_DIR env var generated by build.rs
        let locale_dir = env!("LOCALE_DIR");
        // Note: eprintln! is intentional here — runs before tracing is initialized
        if let Err(e) = gettextrs::bindtextdomain("gcodekit5", locale_dir) {
            eprintln!("bindtextdomain failed: {}", e);
        }
        // Note: eprintln! is intentional here — runs before tracing is initialized
        if let Err(e) = gettextrs::textdomain("gcodekit5") {
            eprintln!("textdomain failed: {}", e);
        }
    });
}

#[macro_export]
macro_rules! t {
    ($s:expr) => {
        gettextrs::gettext($s)
    };
    ($s:expr, $($args:tt)*) => {
        format!(gettextrs::gettext($s), $($args)*)
    };
}
