use gcodekit5_communication::firmware::grbl::settings::Setting;

use super::ConfigSettingsView;

impl ConfigSettingsView {
    pub(crate) fn load_default_grbl_settings(&self) {
        let mut manager = self.settings_manager.borrow_mut();
        manager.clear();

        // Load standard GRBL settings definitions
        for (number, name, description, read_only, unit) in Self::grbl_settings_definitions() {
            manager.set_setting(Setting {
                number,
                name: name.to_string(),
                value: "0".to_string(),
                numeric_value: Some(0.0),
                description: description.to_string(),
                range: None,
                read_only,
                unit: if unit.is_empty() {
                    None
                } else {
                    Some(unit.to_string())
                },
            });
        }
    }

    pub(crate) fn grbl_settings_definitions(
    ) -> Vec<(u16, &'static str, &'static str, bool, &'static str)> {
        vec![
            // Standard GRBL Settings (0-132)
            (
                0,
                "Step Pulse",
                "Step pulse duration in microseconds",
                false,
                "usec",
            ),
            (
                1,
                "Step Idle Delay",
                "Step idle delay in milliseconds",
                false,
                "ms",
            ),
            (
                2,
                "Step Port Invert",
                "Step port invert mask",
                false,
                "mask",
            ),
            (
                3,
                "Direction Port Invert",
                "Direction port invert mask",
                false,
                "mask",
            ),
            (
                4,
                "Step Enable Invert",
                "Invert step enable pin",
                false,
                "bool",
            ),
            (5, "Limit Pins Invert", "Invert limit pins", false, "bool"),
            (6, "Probe Pin Invert", "Invert probe pin", false, "bool"),
            (
                10,
                "Status Report",
                "Status report options mask",
                false,
                "mask",
            ),
            (
                11,
                "Junction Deviation",
                "Junction deviation in mm",
                false,
                "mm",
            ),
            (12, "Arc Tolerance", "Arc tolerance in mm", false, "mm"),
            (
                13,
                "Report Inches",
                "Report in inches instead of mm",
                false,
                "bool",
            ),
            (20, "Soft Limits", "Enable soft limits", false, "bool"),
            (21, "Hard Limits", "Enable hard limits", false, "bool"),
            (22, "Homing Cycle", "Enable homing cycle", false, "bool"),
            (
                23,
                "Homing Dir Invert",
                "Homing direction invert mask",
                false,
                "mask",
            ),
            (
                24,
                "Homing Feed",
                "Homing feed rate in mm/min",
                false,
                "mm/min",
            ),
            (
                25,
                "Homing Seek",
                "Homing seek rate in mm/min",
                false,
                "mm/min",
            ),
            (26, "Homing Debounce", "Homing debounce in ms", false, "ms"),
            (
                27,
                "Homing Pull-Off",
                "Homing pull-off distance in mm",
                false,
                "mm",
            ),
            (28, "G73 Retract", "G73 retract distance in mm", false, "mm"),
            (
                29,
                "Pulse Delay",
                "Pulse delay in microseconds",
                false,
                "usec",
            ),
            (
                30,
                "Max Spindle Speed",
                "Maximum spindle speed in RPM",
                false,
                "RPM",
            ),
            (
                31,
                "Min Spindle Speed",
                "Minimum spindle speed in RPM",
                false,
                "RPM",
            ),
            (32, "Laser Mode", "Enable laser mode", false, "bool"),
            (
                33,
                "Spindle PWM Freq",
                "Spindle PWM frequency in Hz",
                false,
                "Hz",
            ),
            (34, "Spindle PWM Off", "Spindle PWM off value", false, "%"),
            (35, "Spindle PWM Min", "Spindle PWM min value", false, "%"),
            (36, "Spindle PWM Max", "Spindle PWM max value", false, "%"),
            (
                37,
                "Stepper Deenergize",
                "Stepper deenergize mask",
                false,
                "mask",
            ),
            (
                38,
                "Spindle Encoder",
                "Spindle encoder pulses per rev",
                false,
                "PPR",
            ),
            (39, "Legacy RT", "Enable legacy RT commands", false, "bool"),
            (
                40,
                "Limit Pins Invert",
                "Limit pins invert mask",
                false,
                "mask",
            ),
            (41, "Probe Invert", "Probe invert", false, "bool"),
            (43, "Homing Passes", "Homing passes", false, "count"),
            (44, "Homing Cycle 1", "Axes homing cycle 1", false, "mask"),
            (45, "Homing Cycle 2", "Axes homing cycle 2", false, "mask"),
            (46, "Homing Cycle 3", "Axes homing cycle 3", false, "mask"),
            (
                50,
                "Step Jog Speed",
                "Step jog speed in mm/min",
                false,
                "mm/min",
            ),
            (
                51,
                "Slow Jog Speed",
                "Slow jog speed in mm/min",
                false,
                "mm/min",
            ),
            (
                52,
                "Fast Jog Speed",
                "Fast jog speed in mm/min",
                false,
                "mm/min",
            ),
            (
                53,
                "Step Jog Distance",
                "Step jog distance in mm",
                false,
                "mm",
            ),
            (
                54,
                "Slow Jog Distance",
                "Slow jog distance in mm",
                false,
                "mm",
            ),
            (
                55,
                "Fast Jog Distance",
                "Fast jog distance in mm",
                false,
                "mm",
            ),
            (56, "Parking Enable", "Enable parking", false, "bool"),
            (57, "Parking Axis", "Parking axis", false, "axis"),
            (
                58,
                "Parking Pullout Inc",
                "Parking pullout increment",
                false,
                "mm",
            ),
            (
                59,
                "Parking Pullout Rate",
                "Parking pullout rate in mm/min",
                false,
                "mm/min",
            ),
            (60, "Restore Overrides", "Restore overrides", false, "bool"),
            (61, "Safety Door", "Enable safety door", false, "bool"),
            (62, "Sleep Enable", "Enable sleep mode", false, "bool"),
            (63, "Feed Hold Actions", "Feed hold actions", false, "mask"),
            (
                64,
                "Force Init Alarm",
                "Force initialization alarm",
                false,
                "bool",
            ),
            (
                65,
                "Probe Feed Override",
                "Probe allow feed override",
                false,
                "bool",
            ),
            (70, "Network Services", "Network services", false, "mask"),
            (71, "WiFi Mode", "WiFi mode", false, "mode"),
            (72, "Telnet Port", "Telnet port", false, "port"),
            (73, "WebSocket Port", "WebSocket port", false, "port"),
            (74, "HTTP Port", "HTTP port", false, "port"),
            (
                75,
                "Bluetooth Name",
                "Bluetooth service name",
                false,
                "string",
            ),
            (100, "X Steps/mm", "X-axis steps per mm", false, "steps/mm"),
            (101, "Y Steps/mm", "Y-axis steps per mm", false, "steps/mm"),
            (102, "Z Steps/mm", "Z-axis steps per mm", false, "steps/mm"),
            (103, "A Steps/mm", "A-axis steps per mm", false, "steps/mm"),
            (104, "B Steps/mm", "B-axis steps per mm", false, "steps/mm"),
            (105, "C Steps/mm", "C-axis steps per mm", false, "steps/mm"),
            (
                110,
                "X Max Rate",
                "X-axis maximum rate in mm/min",
                false,
                "mm/min",
            ),
            (
                111,
                "Y Max Rate",
                "Y-axis maximum rate in mm/min",
                false,
                "mm/min",
            ),
            (
                112,
                "Z Max Rate",
                "Z-axis maximum rate in mm/min",
                false,
                "mm/min",
            ),
            (
                113,
                "A Max Rate",
                "A-axis maximum rate in mm/min",
                false,
                "mm/min",
            ),
            (
                114,
                "B Max Rate",
                "B-axis maximum rate in mm/min",
                false,
                "mm/min",
            ),
            (
                115,
                "C Max Rate",
                "C-axis maximum rate in mm/min",
                false,
                "mm/min",
            ),
            (
                120,
                "X Acceleration",
                "X-axis acceleration in mm/sec²",
                false,
                "mm/sec²",
            ),
            (
                121,
                "Y Acceleration",
                "Y-axis acceleration in mm/sec²",
                false,
                "mm/sec²",
            ),
            (
                122,
                "Z Acceleration",
                "Z-axis acceleration in mm/sec²",
                false,
                "mm/sec²",
            ),
            (
                123,
                "A Acceleration",
                "A-axis acceleration in mm/sec²",
                false,
                "mm/sec²",
            ),
            (
                124,
                "B Acceleration",
                "B-axis acceleration in mm/sec²",
                false,
                "mm/sec²",
            ),
            (
                125,
                "C Acceleration",
                "C-axis acceleration in mm/sec²",
                false,
                "mm/sec²",
            ),
            (
                130,
                "X Max Travel",
                "X-axis maximum travel in mm",
                false,
                "mm",
            ),
            (
                131,
                "Y Max Travel",
                "Y-axis maximum travel in mm",
                false,
                "mm",
            ),
            (
                132,
                "Z Max Travel",
                "Z-axis maximum travel in mm",
                false,
                "mm",
            ),
            (
                133,
                "A Max Travel",
                "A-axis maximum travel in mm",
                false,
                "mm",
            ),
            (
                134,
                "B Max Travel",
                "B-axis maximum travel in mm",
                false,
                "mm",
            ),
            (
                135,
                "C Max Travel",
                "C-axis maximum travel in mm",
                false,
                "mm",
            ),
            // grblHAL Extended Settings (200+)
            (
                200,
                "Trinamic Driver",
                "Trinamic driver enable",
                false,
                "bool",
            ),
            (201, "Trinamic Homing", "Homing sensitivity", false, ""),
            (
                202,
                "Trinamic Hold %",
                "Hold current percentage",
                false,
                "%",
            ),
            (203, "Trinamic Run %", "Run current percentage", false, "%"),
            (
                204,
                "Trinamic HW %",
                "Hardware current percentage",
                false,
                "%",
            ),
            (
                205,
                "Step Interpolation",
                "Step interpolation enable",
                false,
                "bool",
            ),
            (206, "PWM Chop Config", "PWM chopper config", false, ""),
            (207, "PWM Mode", "PWM mode", false, ""),
            (208, "PWM Freq", "PWM frequency", false, "Hz"),
            (209, "PWM Autoscale", "PWM autoscale", false, "bool"),
            (210, "PWM Autograd", "PWM autograd", false, "bool"),
            (300, "Hostname", "Network hostname", false, "string"),
            (301, "IP Mode", "IP address mode", false, "mode"),
            (302, "IP Address", "IP address", false, "ip"),
            (303, "Gateway", "Gateway address", false, "ip"),
            (304, "Netmask", "Network mask", false, "ip"),
            (305, "Telnet Port", "Telnet port number", false, "port"),
            (306, "HTTP Port", "HTTP port number", false, "port"),
            (
                307,
                "WebSocket Port",
                "WebSocket port number",
                false,
                "port",
            ),
            (308, "FTP Port", "FTP port number", false, "port"),
            (309, "WiFi SSID", "WiFi SSID", false, "string"),
            (310, "WiFi Password", "WiFi password", false, "string"),
            (
                320,
                "Bluetooth Device",
                "Bluetooth device name",
                false,
                "string",
            ),
            (
                321,
                "Bluetooth Service",
                "Bluetooth service name",
                false,
                "string",
            ),
            (340, "Tool Change Mode", "Tool change mode", false, "mode"),
            (
                341,
                "Tool Probe Dist",
                "Tool change probing distance in mm",
                false,
                "mm",
            ),
            (
                342,
                "Tool Locate Feed",
                "Tool change locate feed rate in mm/min",
                false,
                "mm/min",
            ),
            (
                343,
                "Tool Search Seek",
                "Tool change search seek rate in mm/min",
                false,
                "mm/min",
            ),
            (
                344,
                "Tool Pulloff Rate",
                "Tool change probe pull-off rate in mm/min",
                false,
                "mm/min",
            ),
            (370, "Invert I/O", "Invert I/O port pins", false, "mask"),
            (
                371,
                "Invert Analog 0",
                "Invert analog port 0",
                false,
                "bool",
            ),
            (
                372,
                "Invert Analog 1",
                "Invert analog port 1",
                false,
                "bool",
            ),
            (
                384,
                "G92 Persistence",
                "Disable G92 persistence",
                false,
                "bool",
            ),
            (
                385,
                "Dual Axis Offset",
                "Dual axis length offset in mm",
                false,
                "mm",
            ),
            (395, "Startup Line 0", "Startup line 0", false, "gcode"),
            (396, "Startup Line 1", "Startup line 1", false, "gcode"),
            (397, "Startup Line 2", "Startup line 2", false, "gcode"),
            (481, "Autoreport", "Autoreport interval in ms", false, "ms"),
            (550, "Plasma THC", "Enable plasma THC", false, "bool"),
            (551, "Plasma THC Mode", "THC mode", false, "mode"),
            (
                552,
                "Plasma THC Delay",
                "THC delay in seconds",
                false,
                "sec",
            ),
            (
                553,
                "Plasma Threshold",
                "THC threshold in volts",
                false,
                "V",
            ),
            (554, "Plasma P Gain", "THC P gain", false, ""),
            (555, "Plasma I Gain", "THC I gain", false, ""),
            (556, "Plasma D Gain", "THC D gain", false, ""),
            (557, "Arc Voltage Scale", "Arc voltage scale", false, ""),
            (558, "Arc Voltage Offset", "Arc voltage offset", false, "V"),
            (559, "THC VAD Threshold", "VAD threshold", false, ""),
            (560, "THC Void Override", "Void override", false, ""),
            (600, "Encoder Mode", "Encoder mode", false, "mode"),
            (
                601,
                "Encoder CPR",
                "Encoder counts per revolution",
                false,
                "CPR",
            ),
            (
                602,
                "Encoder DPR",
                "Encoder distance per revolution in mm",
                false,
                "mm/rev",
            ),
            (
                603,
                "Encoder Feed Rate",
                "Encoder feed rate in mm/min",
                false,
                "mm/min",
            ),
            (650, "Modbus Baud", "Modbus baud rate", false, "baud"),
            (
                651,
                "Modbus RX Timeout",
                "Modbus RX timeout in ms",
                false,
                "ms",
            ),
            (680, "RS485 Baud", "RS485 baud rate", false, "baud"),
        ]
    }
}
